### ISSUE TITLE
Data Generating Code in Extended Binomial Vignette?

### ISSUE THREAD

**Issue by awhug** [debruine/lmem_sim#1]
Hi Lisa!

Fantastic manuscript and really useful resource. Just a quick question - I could be entirely wrong here, but is there an error in the extended binomial simulation vignette?

https://github.com/debruine/lmem_sim/blob/eb25e36b7bf80a05cabc72e68ea06981b8791f8d/vignettes/appendix3b_extended_binomial.Rmd#L149-L153

I would have assumed that `B_e = beta_e + S_e + I_e`, and `B_c = beta_c + S_c`. But perhaps there's some simple algebraic reason (relating to the interaction?) that this simulation code works?

**Comment by debruine** [comment]
Good catch, thanks!!
